@baseUrl = http://localhost:8080
@accessToken = paste-access-token-here

POST {{baseUrl}}/api/carriers
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{accessToken}}

{
  "name": "Enterprise",
  "nation": "United States",
  "carrierType": "AIRCRAFT_CARRIER",
  "commandCenter": {
    "codeName": "Bridge",
    "securityLevel": 5
  },
  "aircrafts": [
    {
      "model": "F/A-18",
      "manufacturer": "McDonnell Douglas"
    }
  ]
}
